interface TaskSidebarProps {
  open: boolean;
  onClose: () => void;
}

interface SectionProps {
  title: string;
  icon: React.ReactNode;
  children: React.ReactNode;
}

function Section({ title, icon, children }: SectionProps) {
  return (
    <div className="space-y-2.5 rounded-xl border border-border bg-surface p-3.5">
      <div className="flex items-center gap-2">
        <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md border border-border bg-surface-hover text-muted-foreground">
          {icon}
        </div>
        <span className="text-[12px] font-semibold text-foreground">{title}</span>
      </div>
      <p className="text-[11.5px] leading-relaxed text-muted-foreground">{children}</p>
    </div>
  );
}

export default function TaskSidebar({ open, onClose }: TaskSidebarProps) {
  return (
    <div
      className="flex h-full shrink-0 flex-col overflow-hidden border-l border-border bg-sidebar transition-all duration-200 ease-in-out"
      style={{
        width: open ? 288 : 0,
        minWidth: open ? 288 : 0,
        opacity: open ? 1 : 0,
        borderLeftWidth: open ? 1 : 0,
      }}
    >
      <div className="flex h-full shrink-0 flex-col" style={{ width: 288 }}>
        <div className="flex h-10 shrink-0 items-center justify-between border-b border-border px-4">
          <span className="text-[13px] font-semibold text-foreground">Task</span>
          <button
            onClick={onClose}
            className="flex h-6 w-6 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-surface-hover hover:text-foreground"
            title="Close Task Sidebar"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.25" strokeLinecap="round">
              <path d="M18 6L6 18M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div className="flex-1 space-y-3 overflow-y-auto p-3.5">
          <Section
            title="Plan"
            icon={
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2" />
              </svg>
            }
          >
            No active plan. Start an agent to see its step-by-step plan here.
          </Section>

          <Section
            title="Artifacts"
            icon={
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <polygon points="12 2 2 7 12 12 22 7 12 2" />
                <polyline points="2 17 12 22 22 17" />
                <polyline points="2 12 12 17 22 12" />
              </svg>
            }
          >
            Files and outputs generated by the agent will appear here.
          </Section>

          <Section
            title="Sources"
            icon={
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
                <polyline points="22 4 12 14.01 9 11.01" />
              </svg>
            }
          >
            Referenced files and context will be listed here.
          </Section>
        </div>
      </div>
    </div>
  );
}
