import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { Effect } from "effect";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { client } from "../opencode/client";
import { string_content } from "../opencode/types";
import { manager } from "./manager";
import { scan_info } from "./list";
import {
  sanitizeTitle,
  generateSessionTitle,
  pendingOrCompletedTitleSessions,
  clearPendingTitleSessions,
} from "./title";

const originalFetch = globalThis.fetch;

afterEach(() => {
  globalThis.fetch = originalFetch;
  clearPendingTitleSessions();
});

describe("fast automatic session titles", () => {
  describe("title sanitization", () => {
    it("strips wrapping quotes and backticks", () => {
      expect(sanitizeTitle('"Build Auth System"')).toBe("Build Auth System");
      expect(sanitizeTitle("'Fix Bun Test Failures'")).toBe("Fix Bun Test Failures");
      expect(sanitizeTitle("`Refactor Session Manager`")).toBe("Refactor Session Manager");
    });

    it("replaces newlines with spaces", () => {
      expect(sanitizeTitle("Line One\nLine Two\r\nLine Three")).toBe("Line One Line Two Line Three");
    });

    it("strips markdown headers, prefixes, and inline formatting", () => {
      expect(sanitizeTitle("## Title: **OAuth Integration**")).toBe("OAuth Integration");
      expect(sanitizeTitle("Session Title: `Fix Memory Leak`")).toBe("Fix Memory Leak");
      expect(sanitizeTitle("Topic: *Refactor Agent Loop*")).toBe("Refactor Agent Loop");
    });

    it("caps length to around 60 characters smartly", () => {
      const longTitle = "This is a very long title generated by the model that exceeds sixty characters in total length";
      const sanitized = sanitizeTitle(longTitle);
      expect(sanitized.length).toBeLessThanOrEqual(60);
      expect(sanitized).toBe("This is a very long title generated by the model that");
    });

    it("returns empty string for empty or invalid input", () => {
      expect(sanitizeTitle("")).toBe("");
      expect(sanitizeTitle("   ")).toBe("");
    });
  });

  describe("title generation & fallback", () => {
    it("generates and sanitizes title using provider client without reasoning overhead", async () => {
      let requestBody: any
      globalThis.fetch = (async (_input: RequestInfo | URL, init?: RequestInit) => {
        requestBody = init?.body ? JSON.parse(String(init.body)) : null
        return new Response(
          JSON.stringify({
            choices: [
              {
                message: { role: "assistant", content: string_content(' "Create User Login View" ') },
                finish_reason: "stop",
              },
            ],
          }),
          { status: 200 },
        );
      }) as typeof fetch;

      const api = new client("https://provider.invalid", "key", "model");
      const title = await Effect.runPromise(
        generateSessionTitle(api, "Can you create a user login view in React?"),
      );

      expect(title).toBe("Create User Login View");
      expect(requestBody.thinking).toEqual({ type: "disabled" });
      expect(requestBody.max_tokens).toBe(20);
    });

    it("silently falls back (returns empty string) on timeout or provider failure", async () => {
      globalThis.fetch = ((_input: RequestInfo | URL, init?: RequestInit) =>
        new Promise<Response>((_resolve, reject) => {
          init?.signal?.addEventListener("abort", () => reject(init.signal?.reason), { once: true });
        })) as typeof fetch;

      const api = new client("https://provider.invalid", "key", "model");
      const title = await Effect.runPromise(
        generateSessionTitle(api, "Hello world", undefined, 5),
      );

      expect(title).toBe("");
    });
  });

  describe("one-shot tracking and session persistence", () => {
    it("tracks pending/completed title sessions for one-shot behavior", () => {
      clearPendingTitleSessions();
      const sessionId = "session_12345";
      expect(pendingOrCompletedTitleSessions.has(sessionId)).toBe(false);

      pendingOrCompletedTitleSessions.add(sessionId);
      expect(pendingOrCompletedTitleSessions.has(sessionId)).toBe(true);
    });

    it("persists title in session manager and recovers it via scan_info", async () => {
      const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "hollow-title-test-"));
      try {
        const m = new manager();
        m.set_cwd(tmpDir);
        m.set_session_dir(tmpDir);
        await Effect.runPromise(m.new_session());

        // Add a user message and assistant message to allow flushing
        await Effect.runPromise(m.append_message({ role: "user", content: string_content("Initial user prompt") }));
        await Effect.runPromise(m.append_message({ role: "assistant", content: string_content("Initial assistant response") }));

        // Initially no title
        expect(m.get_title()).toBe("");

        // Set title
        const titleText = "Custom Session Title";
        await Effect.runPromise(m.set_title(titleText));
        expect(m.get_title()).toBe(titleText);

        const sessionPath = m.session_file();

        // Reload via scan_info
        const info = await Effect.runPromise(scan_info(sessionPath));
        expect(info.title).toBe(titleText);
        expect(info.first_message).toBe("Initial user prompt");

        // Reload via manager open_file
        const m2 = new manager();
        await Effect.runPromise(m2.open_file(sessionPath));
        expect(m2.get_title()).toBe(titleText);
      } finally {
        await fs.rm(tmpDir, { recursive: true, force: true });
      }
    });
  });

  describe("background title generation hook", () => {
    it("invokes background generation, persists title, and emits session_info_changed event", async () => {
      const { New } = await import("../agent/register");
      const { start_new } = await import("./manager");
      const { mapAgentEvent } = await import("../../runtime/ipc/event_mapper");

      const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "hollow-title-bg-test-"));
      try {
        const sm = await Effect.runPromise(start_new(tmpDir));
        const dummyConfig: any = {
          endpoint: "https://provider.invalid",
          api_key: "key",
          provider: "opencode-go",
          model: "model",
          mcp_servers: {},
          skills: { enabled: false },
          memory: { memory_enabled: false },
          evidence: { enabled: true, verifier_enabled: false, goal_lock_enabled: true },
          compaction: { enabled: false },
        };

        const agent = New(dummyConfig, tmpDir, sm);
        agent.titleGenerator = (client, userText, assistantText) => {
          expect(userText).toBe("User prompt for title");
          return Effect.succeed("Mock Generated Title");
        };

        // Mock runLoop on agent so prompt doesn't call an external LLM
        (agent as any).runLoop = async () => {
          await Effect.runPromise(sm.append_message({ role: "assistant", content: string_content("Assistant response") }));
        };

        const events: any[] = [];
        const emit = (ev: any) => events.push(ev);

        const controller = new AbortController();
        await agent.prompt(controller.signal, dummyConfig, "User prompt for title", null, "", emit);

        // Wait for background title promise to settle
        await new Promise((r) => setTimeout(r, 100));

        expect(sm.get_title()).toBe("Mock Generated Title");

        // Verify scan_info reads persisted title from disk
        const info = await Effect.runPromise(scan_info(sm.session_file()));
        expect(info.title).toBe("Mock Generated Title");

        // Verify session_info_changed event was emitted and mapped for IPC
        const changeEvent = events.find((e) => e.kind === "session_info_changed");
        expect(changeEvent).toBeDefined();
        expect(changeEvent.data).toEqual({ session_id: sm.session_id(), name: "Mock Generated Title" });

        const ipcMapped = mapAgentEvent(changeEvent);
        expect(ipcMapped).toEqual({
          type: "session_info_changed",
          data: { session_id: sm.session_id(), name: "Mock Generated Title" },
        });
      } finally {
        await fs.rm(tmpDir, { recursive: true, force: true });
      }
    });
  });
});
