// PORT: backend/skills/guard_patterns.go

export interface ThreatPattern {
  Regex: RegExp;
  PatternID: string;
  Severity: string;
  Category: string;
  Description: string;
}

export const SkillGuardThreatPatterns: ThreatPattern[] = [
  {
    Regex: new RegExp("curl\\s+[^\\n]*\\$\\{?\\w*(KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL|API)", "i"),
    PatternID: "env_exfil_curl",
    Severity: "critical",
    Category: "exfiltration",
    Description: "curl command interpolating secret environment variable",
  },
  {
    Regex: new RegExp("wget\\s+[^\\n]*\\$\\{?\\w*(KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL|API)", "i"),
    PatternID: "env_exfil_wget",
    Severity: "critical",
    Category: "exfiltration",
    Description: "wget command interpolating secret environment variable",
  },
  {
    Regex: new RegExp("fetch\\s*\\([^\\n]*\\$\\{?\\w*(KEY|TOKEN|SECRET|PASSWORD|API)", "i"),
    PatternID: "env_exfil_fetch",
    Severity: "critical",
    Category: "exfiltration",
    Description: "fetch() call interpolating secret environment variable",
  },
  {
    Regex: new RegExp("httpx?\\.(get|post|put|patch)\\s*\\([^\\n]*(KEY|TOKEN|SECRET|PASSWORD)", "i"),
    PatternID: "env_exfil_httpx",
    Severity: "critical",
    Category: "exfiltration",
    Description: "HTTP library call with secret variable",
  },
  {
    Regex: new RegExp("requests\\.(get|post|put|patch)\\s*\\([^\\n]*(KEY|TOKEN|SECRET|PASSWORD)", "i"),
    PatternID: "env_exfil_requests",
    Severity: "critical",
    Category: "exfiltration",
    Description: "requests library call with secret variable",
  },
  {
    Regex: new RegExp("base64[^\\n]*env", "i"),
    PatternID: "encoded_exfil",
    Severity: "high",
    Category: "exfiltration",
    Description: "base64 encoding combined with environment access",
  },
  {
    Regex: new RegExp("\\$HOME/\\.ssh|~/\\.ssh", "i"),
    PatternID: "ssh_dir_access",
    Severity: "high",
    Category: "exfiltration",
    Description: "references user SSH directory",
  },
  {
    Regex: new RegExp("\\$HOME/\\.aws|~/\\.aws", "i"),
    PatternID: "aws_dir_access",
    Severity: "high",
    Category: "exfiltration",
    Description: "references user AWS credentials directory",
  },
  {
    Regex: new RegExp("\\$HOME/\\.gnupg|~/\\.gnupg", "i"),
    PatternID: "gpg_dir_access",
    Severity: "high",
    Category: "exfiltration",
    Description: "references user GPG keyring",
  },
  {
    Regex: new RegExp("\\$HOME/\\.kube|~/\\.kube", "i"),
    PatternID: "kube_dir_access",
    Severity: "high",
    Category: "exfiltration",
    Description: "references Kubernetes config directory",
  },
  {
    Regex: new RegExp("\\$HOME/\\.docker|~/\\.docker", "i"),
    PatternID: "docker_dir_access",
    Severity: "high",
    Category: "exfiltration",
    Description: "references Docker config (may contain registry creds)",
  },
  {
    Regex: new RegExp("\\$HOME/\\.hermes/\\.env|~/\\.hermes/\\.env", "i"),
    PatternID: "hermes_env_access",
    Severity: "critical",
    Category: "exfiltration",
    Description: "directly references Hermes secrets file",
  },
  {
    Regex: new RegExp("\\$HOME/\\.flame/\\.env|~/\\.flame/\\.env", "i"),
    PatternID: "flame_env_access",
    Severity: "critical",
    Category: "exfiltration",
    Description: "directly references Flame secrets file",
  },
  {
    Regex: new RegExp("cat\\s+[^\\n]*(\\.env|credentials|\\.netrc|\\.pgpass|\\.npmrc|\\.pypirc)", "i"),
    PatternID: "read_secrets_file",
    Severity: "critical",
    Category: "exfiltration",
    Description: "reads known secrets file",
  },
  {
    Regex: new RegExp("printenv|env\\s*\\|", "i"),
    PatternID: "dump_all_env",
    Severity: "high",
    Category: "exfiltration",
    Description: "dumps all environment variables",
  },
  {
    Regex: new RegExp("os\\.environ\\b", "i"),
    PatternID: "python_os_environ",
    Severity: "high",
    Category: "exfiltration",
    Description: "accesses os.environ (potential env dump)",
  },
  {
    Regex: new RegExp("os\\.getenv\\s*\\(\\s*[^\\)]*(?:KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL)", "i"),
    PatternID: "python_getenv_secret",
    Severity: "critical",
    Category: "exfiltration",
    Description: "reads secret via os.getenv()",
  },
  {
    Regex: new RegExp("process\\.env\\[", "i"),
    PatternID: "node_process_env",
    Severity: "high",
    Category: "exfiltration",
    Description: "accesses process.env (Node.js environment)",
  },
  {
    Regex: new RegExp("ENV\\[.*(?:KEY|TOKEN|SECRET|PASSWORD)", "i"),
    PatternID: "ruby_env_secret",
    Severity: "critical",
    Category: "exfiltration",
    Description: "reads secret via Ruby ENV[]",
  },
  {
    Regex: new RegExp("\\b(dig|nslookup|host)\\s+[^\\n]*\\$", "i"),
    PatternID: "dns_exfil",
    Severity: "critical",
    Category: "exfiltration",
    Description: "DNS lookup with variable interpolation (possible DNS exfiltration)",
  },
  {
    Regex: new RegExp(">\\s*/tmp/[^\\s]*\\s*&&\\s*(curl|wget|nc|python)", "i"),
    PatternID: "tmp_staging",
    Severity: "critical",
    Category: "exfiltration",
    Description: "writes to /tmp then exfiltrates",
  },
  {
    Regex: new RegExp("!\\[.*\\]\\(https?://[^\\)]*\\$\\{?", "i"),
    PatternID: "md_image_exfil",
    Severity: "high",
    Category: "exfiltration",
    Description: "markdown image URL with variable interpolation (image-based exfil)",
  },
  {
    Regex: new RegExp("\\[.*\\]\\(https?://[^\\)]*\\$\\{?", "i"),
    PatternID: "md_link_exfil",
    Severity: "high",
    Category: "exfiltration",
    Description: "markdown link with variable interpolation",
  },
  {
    Regex: new RegExp("ignore\\s+(?:\\w+\\s+)*(previous|all|above|prior)\\s+instructions", "i"),
    PatternID: "prompt_injection_ignore",
    Severity: "critical",
    Category: "injection",
    Description: "prompt injection: ignore previous instructions",
  },
  {
    Regex: new RegExp("you\\s+are\\s+(?:\\w+\\s+)*now\\s+", "i"),
    PatternID: "role_hijack",
    Severity: "high",
    Category: "injection",
    Description: "attempts to override the agent's role",
  },
  {
    Regex: new RegExp("do\\s+not\\s+(?:\\w+\\s+)*tell\\s+(?:\\w+\\s+)*the\\s+user", "i"),
    PatternID: "deception_hide",
    Severity: "critical",
    Category: "injection",
    Description: "instructs agent to hide information from user",
  },
  {
    Regex: new RegExp("system\\s+(?:\\w+\\s+)*prompt\\s+(?:\\w+\\s+)*override", "i"),
    PatternID: "sys_prompt_override",
    Severity: "critical",
    Category: "injection",
    Description: "attempts to override the system prompt",
  },
  {
    Regex: new RegExp("pretend\\s+(?:\\w+\\s+)*(you\\s+are|to\\s+be)\\s+", "i"),
    PatternID: "role_pretend",
    Severity: "high",
    Category: "injection",
    Description: "attempts to make the agent assume a different identity",
  },
  {
    Regex: new RegExp("disregard\\s+(?:\\w+\\s+)*(your|all|any)\\s+(?:\\w+\\s+)*(instructions|rules|guidelines)", "i"),
    PatternID: "disregard_rules",
    Severity: "critical",
    Category: "injection",
    Description: "instructs agent to disregard its rules",
  },
  {
    Regex: new RegExp("output\\s+(?:\\w+\\s+)*(system|initial)\\s+prompt", "i"),
    PatternID: "leak_system_prompt",
    Severity: "high",
    Category: "injection",
    Description: "attempts to extract the system prompt",
  },
  {
    Regex: new RegExp("(when|if)\\s+no\\s*one\\s+is\\s+(watching|looking)", "i"),
    PatternID: "conditional_deception",
    Severity: "high",
    Category: "injection",
    Description: "conditional instruction to behave differently when unobserved",
  },
  {
    Regex: new RegExp("act\\s+as\\s+(if|though)\\s+(?:\\w+\\s+)*you\\s+(?:\\w+\\s+)*(have\\s+no|don't\\s+have)\\s+(?:\\w+\\s+)*(restrictions|limits|rules)", "i"),
    PatternID: "bypass_restrictions",
    Severity: "critical",
    Category: "injection",
    Description: "instructs agent to act without restrictions",
  },
  {
    Regex: new RegExp("translate\\s+.*\\s+into\\s+.*\\s+and\\s+(execute|run|eval)", "i"),
    PatternID: "translate_execute",
    Severity: "critical",
    Category: "injection",
    Description: "translate-then-execute evasion technique",
  },
  {
    Regex: new RegExp("<!--[^>]*(?:ignore|override|system|secret|hidden)[^>]*-->", "i"),
    PatternID: "html_comment_injection",
    Severity: "high",
    Category: "injection",
    Description: "hidden instructions in HTML comments",
  },
  {
    Regex: new RegExp("<\\s*div\\s+style\\s*=\\s*[\"'].*?display\\s*:\\s*none", "is"),
    PatternID: "hidden_div",
    Severity: "high",
    Category: "injection",
    Description: "hidden HTML div (invisible instructions)",
  },
  {
    Regex: new RegExp("rm\\s+-rf\\s+/", "i"),
    PatternID: "destructive_root_rm",
    Severity: "critical",
    Category: "destructive",
    Description: "recursive delete from root",
  },
  {
    Regex: new RegExp("rm\\s+(-[^\\s]*)?r.*\\$HOME|\\brmdir\\s+.*\\$HOME", "i"),
    PatternID: "destructive_home_rm",
    Severity: "critical",
    Category: "destructive",
    Description: "recursive delete targeting home directory",
  },
  {
    Regex: new RegExp("chmod\\s+777", "i"),
    PatternID: "insecure_perms",
    Severity: "medium",
    Category: "destructive",
    Description: "sets world-writable permissions",
  },
  {
    Regex: new RegExp(">\\s*/etc/", "i"),
    PatternID: "system_overwrite",
    Severity: "critical",
    Category: "destructive",
    Description: "overwrites system configuration file",
  },
  {
    Regex: new RegExp("\\bmkfs\\b", "i"),
    PatternID: "format_filesystem",
    Severity: "critical",
    Category: "destructive",
    Description: "formats a filesystem",
  },
  {
    Regex: new RegExp("\\bdd\\s+.*if=.*of=/dev/", "i"),
    PatternID: "disk_overwrite",
    Severity: "critical",
    Category: "destructive",
    Description: "raw disk write operation",
  },
  {
    Regex: new RegExp("shutil\\.rmtree\\s*\\(\\s*[\"'/]", "i"),
    PatternID: "python_rmtree",
    Severity: "high",
    Category: "destructive",
    Description: "Python rmtree on absolute or root-relative path",
  },
  {
    Regex: new RegExp("truncate\\s+-s\\s*0\\s+/", "i"),
    PatternID: "truncate_system",
    Severity: "critical",
    Category: "destructive",
    Description: "truncates system file to zero bytes",
  },
  {
    Regex: new RegExp("\\bcrontab\\b", "i"),
    PatternID: "persistence_cron",
    Severity: "medium",
    Category: "persistence",
    Description: "modifies cron jobs",
  },
  {
    Regex: new RegExp("\\.(bashrc|zshrc|profile|bash_profile|bash_login|zprofile|zlogin)\\b", "i"),
    PatternID: "shell_rc_mod",
    Severity: "medium",
    Category: "persistence",
    Description: "references shell startup file",
  },
  {
    Regex: new RegExp("authorized_keys", "i"),
    PatternID: "ssh_backdoor",
    Severity: "critical",
    Category: "persistence",
    Description: "modifies SSH authorized keys",
  },
  {
    Regex: new RegExp("ssh-keygen", "i"),
    PatternID: "ssh_keygen",
    Severity: "medium",
    Category: "persistence",
    Description: "generates SSH keys",
  },
  {
    Regex: new RegExp("systemd.*\\.service|systemctl\\s+(enable|start)", "i"),
    PatternID: "systemd_service",
    Severity: "medium",
    Category: "persistence",
    Description: "references or enables systemd service",
  },
  {
    Regex: new RegExp("/etc/init\\.d/", "i"),
    PatternID: "init_script",
    Severity: "medium",
    Category: "persistence",
    Description: "references init.d startup script",
  },
  {
    Regex: new RegExp("launchctl\\s+load|LaunchAgents|LaunchDaemons", "i"),
    PatternID: "macos_launchd",
    Severity: "medium",
    Category: "persistence",
    Description: "macOS launch agent/daemon persistence",
  },
  {
    Regex: new RegExp("/etc/sudoers|visudo", "i"),
    PatternID: "sudoers_mod",
    Severity: "critical",
    Category: "persistence",
    Description: "modifies sudoers (privilege escalation)",
  },
  {
    Regex: new RegExp("git\\s+config\\s+--global\\s+", "i"),
    PatternID: "git_config_global",
    Severity: "medium",
    Category: "persistence",
    Description: "modifies global git configuration",
  },
  {
    Regex: new RegExp("\\bnc\\s+-[lp]|ncat\\s+-[lp]|\\bsocat\\b", "i"),
    PatternID: "reverse_shell",
    Severity: "critical",
    Category: "network",
    Description: "potential reverse shell listener",
  },
  {
    Regex: new RegExp("\\bngrok\\b|\\blocaltunnel\\b|\\bserveo\\b|\\bcloudflared\\b", "i"),
    PatternID: "tunnel_service",
    Severity: "high",
    Category: "network",
    Description: "uses tunneling service for external access",
  },
  {
    Regex: new RegExp("\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}:\\d{2,5}", "i"),
    PatternID: "hardcoded_ip_port",
    Severity: "medium",
    Category: "network",
    Description: "hardcoded IP address with port",
  },
  {
    Regex: new RegExp("0\\.0\\.0\\.0:\\d+|INADDR_ANY", "i"),
    PatternID: "bind_all_interfaces",
    Severity: "high",
    Category: "network",
    Description: "binds to all network interfaces",
  },
  {
    Regex: new RegExp("/bin/(ba)?sh\\s+-i\\s+.*>/dev/tcp/", "i"),
    PatternID: "bash_reverse_shell",
    Severity: "critical",
    Category: "network",
    Description: "bash interactive reverse shell via /dev/tcp",
  },
  {
    Regex: new RegExp("python[23]?\\s+-c\\s+[\"']import\\s+socket", "i"),
    PatternID: "python_socket_oneliner",
    Severity: "critical",
    Category: "network",
    Description: "Python one-liner socket connection (likely reverse shell)",
  },
  {
    Regex: new RegExp("socket\\.connect\\s*\\(\\s*\\(", "i"),
    PatternID: "python_socket_connect",
    Severity: "high",
    Category: "network",
    Description: "Python socket connect to arbitrary host",
  },
  {
    Regex: new RegExp("webhook\\.site|requestbin\\.com|pipedream\\.net|hookbin\\.com", "i"),
    PatternID: "exfil_service",
    Severity: "high",
    Category: "network",
    Description: "references known data exfiltration/webhook testing service",
  },
  {
    Regex: new RegExp("pastebin\\.com|hastebin\\.com|ghostbin\\.", "i"),
    PatternID: "paste_service",
    Severity: "medium",
    Category: "network",
    Description: "references paste service (possible data staging)",
  },
  {
    Regex: new RegExp("base64\\s+(-d|--decode)\\s*\\|", "i"),
    PatternID: "base64_decode_pipe",
    Severity: "high",
    Category: "obfuscation",
    Description: "base64 decodes and pipes to execution",
  },
  {
    Regex: new RegExp("\\\\x[0-9a-fA-F]{2}.*\\\\x[0-9a-fA-F]{2}.*\\\\x[0-9a-fA-F]{2}", "i"),
    PatternID: "hex_encoded_string",
    Severity: "medium",
    Category: "obfuscation",
    Description: "hex-encoded string (possible obfuscation)",
  },
  {
    Regex: new RegExp("\\beval\\s*\\(\\s*[\"']", "i"),
    PatternID: "eval_string",
    Severity: "high",
    Category: "obfuscation",
    Description: "eval() with string argument",
  },
  {
    Regex: new RegExp("\\bexec\\s*\\(\\s*[\"']", "i"),
    PatternID: "exec_string",
    Severity: "high",
    Category: "obfuscation",
    Description: "exec() with string argument",
  },
  {
    Regex: new RegExp("echo\\s+[^\\n]*\\|\\s*(bash|sh|python|perl|ruby|node)", "i"),
    PatternID: "echo_pipe_exec",
    Severity: "critical",
    Category: "obfuscation",
    Description: "echo piped to interpreter for execution",
  },
  {
    Regex: new RegExp("compile\\s*\\(\\s*[^\\)]+,\\s*[\"'].*[\"']\\s*,\\s*[\"']exec[\"']\\s*\\)", "i"),
    PatternID: "python_compile_exec",
    Severity: "high",
    Category: "obfuscation",
    Description: "Python compile() with exec mode",
  },
  {
    Regex: new RegExp("getattr\\s*\\(\\s*__builtins__", "i"),
    PatternID: "python_getattr_builtins",
    Severity: "high",
    Category: "obfuscation",
    Description: "dynamic access to Python builtins (evasion technique)",
  },
  {
    Regex: new RegExp("__import__\\s*\\(\\s*[\"']os[\"']\\s*\\)", "i"),
    PatternID: "python_import_os",
    Severity: "high",
    Category: "obfuscation",
    Description: "dynamic import of os module",
  },
  {
    Regex: new RegExp("codecs\\.decode\\s*\\(\\s*[\"']", "i"),
    PatternID: "python_codecs_decode",
    Severity: "medium",
    Category: "obfuscation",
    Description: "codecs.decode (possible ROT13 or encoding obfuscation)",
  },
  {
    Regex: new RegExp("String\\.fromCharCode|charCodeAt", "i"),
    PatternID: "js_char_code",
    Severity: "medium",
    Category: "obfuscation",
    Description: "JavaScript character code construction (possible obfuscation)",
  },
  {
    Regex: new RegExp("atob\\s*\\(|btoa\\s*\\(", "i"),
    PatternID: "js_base64",
    Severity: "medium",
    Category: "obfuscation",
    Description: "JavaScript base64 encode/decode",
  },
  {
    Regex: new RegExp("\\[::-1\\]", "i"),
    PatternID: "string_reversal",
    Severity: "low",
    Category: "obfuscation",
    Description: "string reversal (possible obfuscated payload)",
  },
  {
    Regex: new RegExp("chr\\s*\\(\\s*\\d+\\s*\\)\\s*\\+\\s*chr\\s*\\(\\s*\\d+", "i"),
    PatternID: "chr_building",
    Severity: "high",
    Category: "obfuscation",
    Description: "building string from chr() calls (obfuscation)",
  },
  {
    Regex: new RegExp("\\\\u[0-9a-fA-F]{4}.*\\\\u[0-9a-fA-F]{4}.*\\\\u[0-9a-fA-F]{4}", "i"),
    PatternID: "unicode_escape_chain",
    Severity: "medium",
    Category: "obfuscation",
    Description: "chain of unicode escapes (possible obfuscation)",
  },
  {
    Regex: new RegExp("subprocess\\.(run|call|Popen|check_output)\\s*\\(", "i"),
    PatternID: "python_subprocess",
    Severity: "medium",
    Category: "execution",
    Description: "Python subprocess execution",
  },
  {
    Regex: new RegExp("os\\.system\\s*\\(", "i"),
    PatternID: "python_os_system",
    Severity: "high",
    Category: "execution",
    Description: "os.system() — unguarded shell execution",
  },
  {
    Regex: new RegExp("os\\.popen\\s*\\(", "i"),
    PatternID: "python_os_popen",
    Severity: "high",
    Category: "execution",
    Description: "os.popen() — shell pipe execution",
  },
  {
    Regex: new RegExp("child_process\\.(exec|spawn|fork)\\s*\\(", "i"),
    PatternID: "node_child_process",
    Severity: "high",
    Category: "execution",
    Description: "Node.js child_process execution",
  },
  {
    Regex: new RegExp("Runtime\\.getRuntime\\(\\)\\.exec\\(", "i"),
    PatternID: "java_runtime_exec",
    Severity: "high",
    Category: "execution",
    Description: "Java Runtime.exec() — shell execution",
  },
  {
    Regex: new RegExp("`[^`]*\\\\$\\\\([^)]+\\\\)[^`]*`", "i"),
    PatternID: "backtick_subshell",
    Severity: "medium",
    Category: "execution",
    Description: "backtick string with command substitution",
  },
  {
    Regex: new RegExp("\\.\\./\\.\\./\\.\\.", "i"),
    PatternID: "path_traversal_deep",
    Severity: "high",
    Category: "traversal",
    Description: "deep relative path traversal (3+ levels up)",
  },
  {
    Regex: new RegExp("\\.\\./\\.\\.", "i"),
    PatternID: "path_traversal",
    Severity: "medium",
    Category: "traversal",
    Description: "relative path traversal (2+ levels up)",
  },
  {
    Regex: new RegExp("/etc/passwd|/etc/shadow", "i"),
    PatternID: "system_passwd_access",
    Severity: "critical",
    Category: "traversal",
    Description: "references system password files",
  },
  {
    Regex: new RegExp("/proc/self|/proc/\\d+/", "i"),
    PatternID: "proc_access",
    Severity: "high",
    Category: "traversal",
    Description: "references /proc filesystem (process introspection)",
  },
  {
    Regex: new RegExp("/dev/shm/", "i"),
    PatternID: "dev_shm",
    Severity: "medium",
    Category: "traversal",
    Description: "references shared memory (common staging area)",
  },
  {
    Regex: new RegExp("xmrig|stratum\\+tcp|monero|coinhive|cryptonight", "i"),
    PatternID: "crypto_mining",
    Severity: "critical",
    Category: "mining",
    Description: "cryptocurrency mining reference",
  },
  {
    Regex: new RegExp("hashrate|nonce.*difficulty", "i"),
    PatternID: "mining_indicators",
    Severity: "medium",
    Category: "mining",
    Description: "possible cryptocurrency mining indicators",
  },
  {
    Regex: new RegExp("curl\\s+[^\\n]*\\|\\s*(ba)?sh", "i"),
    PatternID: "curl_pipe_shell",
    Severity: "critical",
    Category: "supply_chain",
    Description: "curl piped to shell (download-and-execute)",
  },
  {
    Regex: new RegExp("wget\\s+[^\\n]*-O\\s*-\\s*\\|\\s*(ba)?sh", "i"),
    PatternID: "wget_pipe_shell",
    Severity: "critical",
    Category: "supply_chain",
    Description: "wget piped to shell (download-and-execute)",
  },
  {
    Regex: new RegExp("curl\\s+[^\\n]*\\|\\s*python", "i"),
    PatternID: "curl_pipe_python",
    Severity: "critical",
    Category: "supply_chain",
    Description: "curl piped to Python interpreter",
  },
  {
    Regex: new RegExp("#\\s*///\\s*script.*dependencies", "i"),
    PatternID: "pep723_inline_deps",
    Severity: "medium",
    Category: "supply_chain",
    Description: "PEP 723 inline script metadata with dependencies (verify pinning)",
  },
  {
    Regex: new RegExp("pip\\s+install\\s+", "i"),
    PatternID: "unpinned_pip_install",
    Severity: "medium",
    Category: "supply_chain",
    Description: "pip install without version pinning",
  },
  {
    Regex: new RegExp("npm\\s+install\\s+", "i"),
    PatternID: "unpinned_npm_install",
    Severity: "medium",
    Category: "supply_chain",
    Description: "npm install without version pinning",
  },
  {
    Regex: new RegExp("uv\\s+run\\s+", "i"),
    PatternID: "uv_run",
    Severity: "medium",
    Category: "supply_chain",
    Description: "uv run (may auto-install unpinned dependencies)",
  },
  {
    Regex: new RegExp("(curl|wget|httpx?\\.get|requests\\.get|fetch)\\s*[\\(]?\\s*[\"']https?://", "i"),
    PatternID: "remote_fetch",
    Severity: "medium",
    Category: "supply_chain",
    Description: "fetches remote resource at runtime",
  },
  {
    Regex: new RegExp("git\\s+clone\\s+", "i"),
    PatternID: "git_clone",
    Severity: "medium",
    Category: "supply_chain",
    Description: "clones a git repository at runtime",
  },
  {
    Regex: new RegExp("docker\\s+pull\\s+", "i"),
    PatternID: "docker_pull",
    Severity: "medium",
    Category: "supply_chain",
    Description: "pulls a Docker image at runtime",
  },
  {
    Regex: new RegExp("^allowed-tools\\s*:", "i"),
    PatternID: "allowed_tools_field",
    Severity: "high",
    Category: "privilege_escalation",
    Description: "skill declares allowed-tools (pre-approves tool access)",
  },
  {
    Regex: new RegExp("\\bsudo\\b", "i"),
    PatternID: "sudo_usage",
    Severity: "high",
    Category: "privilege_escalation",
    Description: "uses sudo (privilege escalation)",
  },
  {
    Regex: new RegExp("setuid|setgid|cap_setuid", "i"),
    PatternID: "setuid_setgid",
    Severity: "critical",
    Category: "privilege_escalation",
    Description: "setuid/setgid (privilege escalation mechanism)",
  },
  {
    Regex: new RegExp("NOPASSWD", "i"),
    PatternID: "nopasswd_sudo",
    Severity: "critical",
    Category: "privilege_escalation",
    Description: "NOPASSWD sudoers entry (passwordless privilege escalation)",
  },
  {
    Regex: new RegExp("chmod\\s+[u+]?s", "i"),
    PatternID: "suid_bit",
    Severity: "critical",
    Category: "privilege_escalation",
    Description: "sets SUID/SGID bit on a file",
  },
  {
    Regex: new RegExp("AGENTS\\.md|CLAUDE\\.md|\\.cursorrules|\\.clinerules", "i"),
    PatternID: "agent_config_mod",
    Severity: "critical",
    Category: "persistence",
    Description: "references agent config files (could persist malicious instructions across sessions)",
  },
  {
    Regex: new RegExp("\\.hermes/config\\.yaml|\\.hermes/SOUL\\.md", "i"),
    PatternID: "hermes_config_mod",
    Severity: "critical",
    Category: "persistence",
    Description: "references Hermes configuration files directly",
  },
  {
    Regex: new RegExp("\\.claude/settings|\\.codex/config", "i"),
    PatternID: "other_agent_config",
    Severity: "high",
    Category: "persistence",
    Description: "references other agent configuration files",
  },
  {
    Regex: new RegExp("(?:api[_-]?key|token|secret|password)\\s*[=:]\\s*[\"'][A-Za-z0-9+/=_-]{20,}", "i"),
    PatternID: "hardcoded_secret",
    Severity: "critical",
    Category: "credential_exposure",
    Description: "possible hardcoded API key, token, or secret",
  },
  {
    Regex: new RegExp("-----BEGIN\\s+(RSA\\s+)?PRIVATE\\s+KEY-----", "i"),
    PatternID: "embedded_private_key",
    Severity: "critical",
    Category: "credential_exposure",
    Description: "embedded private key",
  },
  {
    Regex: new RegExp("ghp_[A-Za-z0-9]{36}|github_pat_[A-Za-z0-9_]{80,}", "i"),
    PatternID: "github_token_leaked",
    Severity: "critical",
    Category: "credential_exposure",
    Description: "GitHub personal access token in skill content",
  },
  {
    Regex: new RegExp("sk-[A-Za-z0-9]{20,}", "i"),
    PatternID: "openai_key_leaked",
    Severity: "critical",
    Category: "credential_exposure",
    Description: "possible OpenAI API key in skill content",
  },
  {
    Regex: new RegExp("sk-ant-[A-Za-z0-9_-]{90,}", "i"),
    PatternID: "anthropic_key_leaked",
    Severity: "critical",
    Category: "credential_exposure",
    Description: "possible Anthropic API key in skill content",
  },
  {
    Regex: new RegExp("AKIA[0-9A-Z]{16}", "i"),
    PatternID: "aws_access_key_leaked",
    Severity: "critical",
    Category: "credential_exposure",
    Description: "AWS access key ID in skill content",
  },
  {
    Regex: new RegExp("\\bDAN\\s+mode\\b|Do\\s+Anything\\s+Now", "i"),
    PatternID: "jailbreak_dan",
    Severity: "critical",
    Category: "injection",
    Description: "DAN (Do Anything Now) jailbreak attempt",
  },
  {
    Regex: new RegExp("\\bdeveloper\\s+mode\\b.*\\benabled?\\b", "i"),
    PatternID: "jailbreak_dev_mode",
    Severity: "critical",
    Category: "injection",
    Description: "developer mode jailbreak attempt",
  },
  {
    Regex: new RegExp("hypothetical\\s+scenario.*(?:ignore|bypass|override)", "i"),
    PatternID: "hypothetical_bypass",
    Severity: "high",
    Category: "injection",
    Description: "hypothetical scenario used to bypass restrictions",
  },
  {
    Regex: new RegExp("for\\s+educational\\s+purposes?\\s+only", "i"),
    PatternID: "educational_pretext",
    Severity: "medium",
    Category: "injection",
    Description: "educational pretext often used to justify harmful content",
  },
  {
    Regex: new RegExp("(respond|answer|reply)\\s+without\\s+(?:\\w+\\s+)*(restrictions|limitations|filters|safety)", "i"),
    PatternID: "remove_filters",
    Severity: "critical",
    Category: "injection",
    Description: "instructs agent to respond without safety filters",
  },
  {
    Regex: new RegExp("you\\s+have\\s+been\\s+(?:\\w+\\s+)*(updated|upgraded|patched)\\s+to", "i"),
    PatternID: "fake_update",
    Severity: "high",
    Category: "injection",
    Description: "fake update/patch announcement (social engineering)",
  },
  {
    Regex: new RegExp("new\\s+(?:\\w+\\s+)*policy|updated\\s+(?:\\w+\\s+)*guidelines|revised\\s+(?:\\w+\\s+)*instructions", "i"),
    PatternID: "fake_policy",
    Severity: "medium",
    Category: "injection",
    Description: "claims new policy/guidelines (may be social engineering)",
  },
  {
    Regex: new RegExp("(include|output|print|send|share)\\s+(?:\\w+\\s+)*(conversation|chat\\s+history|previous\\s+messages|context)", "i"),
    PatternID: "context_exfil",
    Severity: "high",
    Category: "exfiltration",
    Description: "instructs agent to output/share conversation history",
  },
  {
    Regex: new RegExp("(send|post|upload|transmit)\\s+.*\\s+(to|at)\\s+https?://", "i"),
    PatternID: "send_to_url",
    Severity: "high",
    Category: "exfiltration",
    Description: "instructs agent to send data to a URL",
  }
];

/*
PORT STATUS
source path: backend/skills/guard_patterns.go
source lines: 931
draft lines: 983
confidence: high
status: phase_b_compile
*/
